# ClientPublicKey = U6/x4k6w+gEMSdvbWkKDuFUIOXwTpAFZzNvp3m5irzQ=

[Interface]
PrivateKey = aFo2EB941x7m6CUs2ejbBjy1vT/x8CI0bXtzw9NeK3s=
Address = 10.8.0.5/32
DNS = 1.1.1.1

[Peer]
PublicKey = w+JEv1CDgtrOduepTLLW90rekFgHwvKoJTBsPEBOXDo=
Endpoint = 117.53.44.59:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
